### PR TITLE
Add support / sponsorship info

### PR DESCRIPTION
**Pull request by clue**

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @clue 
Could you add this file to https://github.com/clue/stream-filter/blob/master/.gitattributes ?

**Comment by SimonFrings** [comment]
Hey @williamdes, I can understand that this is not something necessary for the project but it is important to us.

We love to invest a lot of time into our Open Source projects but we still need to keep our company going. We talked a lot about [sustainable Open Source](https://clue.engineering/2020/introducing-clue-access) in the past and that it's not easy to achieve if you give out your work for free.

That's why we see sponsoring as an opportunity to get one step closer to achieving some kind of sustainability in Open Source. The choice to sponsor us is completely up to you, we would always very much appreciate it and it allows us to put more time into maintaining our projects (or getting new ones out). :+1:

**Comment by williamdes** [comment]
Hi @SimonFrings 

I totally understand, but is this file required in the vendor bundles and on servers ?
From all repositories I did see with this file this is the only one that does not remove it from the vendor bundle

**Comment by SimonFrings** [comment]
We made the decision to keep it out of the `.gitattributes`, it's not a big file so it won't do any harm.

You can always delete the file if you don't want to have it inside your project.

**Pull request merged**
